import mongoose from 'mongoose';
import { Producer } from './models/Producer';
import { Product } from './models/Product';

const MONGO_URI = process.env.MONGODB_URI || 'mongodb+srv://irfantaymas:1453@cluster33.qmvgzmy.mongodb.net/tazekoy';

/* ── Producers ── */
const producers = [
  {
    name: 'Mehmet Yılmaz Çiftliği',
    slug: 'mehmet-yilmaz-ciftligi',
    bio: 'Ege\'nin bereketli topraklarında 30 yıldır organik tarım yapıyoruz.',
    story: 'İzmir\'in Ödemiş ilçesinde üçüncü nesil çiftçiyiz. Kimyasal ilaç kullanmadan, toprağı sevgiyle işliyoruz.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    location: { city: 'İzmir', district: 'Ödemiş', village: 'Birgi', coordinates: { lat: 38.22, lng: 28.00 }, farmName: 'Yılmaz Organik Çiftliği', farmSizeHectares: 12 },
    certificates: [{ name: 'Organik Tarım Sertifikası', issuedBy: 'TÜBİTAK', issuedAt: new Date('2020-03-01'), badgeColor: '#4CAF50' }],
    farmImages: ['https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&q=80'],
    specializations: ['sebze', 'meyve'],
    farmingMethods: ['Organik Tarım', 'Biyodinamik Tarım'],
    rating: 4.8, reviewCount: 142, totalOrders: 890, isVerified: true, isActive: true,
    joinedAt: new Date('2021-01-15'),
  },
  {
    name: 'Anadolu Bahçesi',
    slug: 'anadolu-bahcesi',
    bio: 'Karadeniz\'in serin havasında yetişen doğal ürünleri sofralarınıza taşıyoruz.',
    story: 'Trabzon\'un dağ köylerinde, atalarımızdan öğrendiğimiz yöntemlerle üretiyoruz.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800&q=80',
    location: { city: 'Trabzon', district: 'Maçka', village: 'Hamsiköy', coordinates: { lat: 40.80, lng: 39.74 }, farmName: 'Anadolu Bahçesi', farmSizeHectares: 8 },
    certificates: [{ name: 'Organik Ürün Belgesi', issuedBy: 'TÜRKAK', issuedAt: new Date('2019-06-01'), badgeColor: '#2196F3' }],
    farmImages: ['https://images.unsplash.com/photo-1500076656116-558758c991c1?w=600&q=80'],
    specializations: ['bal-recel', 'süt-ürünleri'],
    farmingMethods: ['Geleneksel Tarım', 'Organik Tarım'],
    rating: 4.9, reviewCount: 98, totalOrders: 560, isVerified: true, isActive: true,
    joinedAt: new Date('2021-04-10'),
  },
  {
    name: 'Ege Zeytinliği',
    slug: 'ege-zeytinligi',
    bio: 'Yüz yıllık zeytin ağaçlarından sızma zeytinyağı ve organik zeytin üretiyoruz.',
    story: 'Ayvalık\'ta beşinci nesil zeytinyağı üreticisiyiz. Taş baskı yöntemiyle soğuk sıkım zeytinyağı yapıyoruz.',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80',
    location: { city: 'Balıkesir', district: 'Ayvalık', coordinates: { lat: 39.32, lng: 26.69 }, farmName: 'Ege Zeytinliği', farmSizeHectares: 25 },
    certificates: [{ name: 'PDO Sertifikası', issuedBy: 'Avrupa Birliği', issuedAt: new Date('2018-09-01'), badgeColor: '#FF9800' }],
    farmImages: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    specializations: ['zeytinyağı'],
    farmingMethods: ['Organik Tarım', 'Geleneksel Taş Baskı'],
    rating: 4.7, reviewCount: 203, totalOrders: 1240, isVerified: true, isActive: true,
    joinedAt: new Date('2020-11-20'),
  },
  {
    name: 'Doğa\'nın Kalbi',
    slug: 'doganin-kalbi',
    bio: 'Güneydoğu Anadolu\'nun zengin topraklarından kuruyemiş ve bakliyat hasadı yapıyoruz.',
    story: 'Şanlıurfa\'da büyük ailemizle birlikte fıstık, antep fıstığı ve bakliyat üretiyoruz.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80',
    location: { city: 'Şanlıurfa', district: 'Merkez', coordinates: { lat: 37.16, lng: 38.79 }, farmName: 'Doğa\'nın Kalbi Çiftliği', farmSizeHectares: 18 },
    certificates: [{ name: 'İyi Tarım Uygulamaları', issuedBy: 'T.C. Tarım Bakanlığı', issuedAt: new Date('2021-02-01'), badgeColor: '#9C27B0' }],
    farmImages: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80'],
    specializations: ['kuruyemiş', 'bakliyat'],
    farmingMethods: ['Organik Tarım'],
    rating: 4.6, reviewCount: 87, totalOrders: 430, isVerified: true, isActive: true,
    joinedAt: new Date('2022-02-05'),
  },
];

/* ── Products ── */
function makeProducts(pIds: mongoose.Types.ObjectId[]) {
  const [yilmaz, anadolu, ege, doga] = pIds;
  const now = new Date();
  const campaign = new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000); // 5 gün sonra

  return [
    /* ─────────── SEBZE ─────────── */
    {
      name: 'Organik Domates', slug: 'organik-domates',
      description: 'Güneşin altında olgunlaşmış, sulu ve aromalı organik domates. Seralarda değil, açık tarlada yetiştirilmiştir.',
      story: 'Mehmet amcamızın tarlasında her yıl Temmuz-Eylül ayları arasında hasat ettiğimiz bu domatesler, kimyasal gübre görmemiştir.',
      producer: yilmaz, category: 'sebze', tags: ['taze', 'organik', 'domates', 'sulu'],
      images: ['https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&q=80', 'https://images.unsplash.com/photo-1561136594-7f68413baa99?w=600&q=80'],
      price: 45, unit: 'kg', stock: 150, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş', farmName: 'Yılmaz Organik Çiftliği' },
      healthBenefits: ['C vitamini kaynağı', 'Antioksidan', 'Kalp dostu'],
      suitableFor: ['Herkes', 'Vejetaryen', 'Vegan'],
      notSuitableFor: [],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: true, isCampaign: false,
      rating: 4.8, reviewCount: 45, soldCount: 320, isActive: true,
    },
    {
      name: 'Sivri Biber', slug: 'sivri-biber',
      description: 'Ege\'nin sıcak iklimiyle yetişen, hem tatlı hem hafif acı sivri biber. Dolmalık ve közlemelik.',
      story: 'İzmir ovalarının bereketli toprağında doğal yöntemlerle yetiştirilen biberler.',
      producer: yilmaz, category: 'sebze', tags: ['taze', 'organik', 'biber', 'acı'],
      images: ['https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&q=80'],
      price: 38, unit: 'kg', stock: 80, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş', farmName: 'Yılmaz Organik Çiftliği' },
      healthBenefits: ['C vitamini', 'Metabolizma hızlandırıcı'],
      suitableFor: ['Herkes', 'Vegan'], notSuitableFor: ['Mide hassasiyeti olanlar'],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: false, isCampaign: false,
      rating: 4.6, reviewCount: 28, soldCount: 180, isActive: true,
    },
    {
      name: 'Kabak (Sakız)', slug: 'sakiz-kabak',
      description: 'Ege\'ye özgü sakız kabağı. Yemeklerde, dolmalarda ve mercimekli yemeklerde muhteşem lezzet verir.',
      story: 'Geleneksel tohumlardan yetiştirilen bu kabak çeşidi, Ege mutfağının vazgeçilmezidir.',
      producer: yilmaz, category: 'sebze', tags: ['taze', 'organik', 'kabak'],
      images: ['https://images.unsplash.com/photo-1596097762881-c4d307ec6abb?w=600&q=80'],
      price: 28, unit: 'kg', stock: 120, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş' },
      healthBenefits: ['Düşük kalori', 'Lif kaynağı', 'B vitamini'],
      suitableFor: ['Herkes', 'Diyabetik', 'Vegan'], notSuitableFor: [],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: false, isCampaign: false,
      rating: 4.5, reviewCount: 19, soldCount: 95, isActive: true,
    },
    {
      name: 'Taze Ispanak', slug: 'taze-ispanak',
      description: 'Demir deposu ıspanak. Sonbahar hasadı, yaprakları kalın ve sulu.',
      story: 'Kış aylarında Ege\'nin ılıman havasında yetiştirilen bu ıspanak, özellikle börek ve yemekler için idealdir.',
      producer: yilmaz, category: 'sebze', tags: ['taze', 'organik', 'ıspanak', 'yeşil'],
      images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&q=80'],
      price: 22, unit: 'demet', stock: 200, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş' },
      healthBenefits: ['Demir kaynağı', 'Folik asit', 'K vitamini'],
      suitableFor: ['Herkes', 'Hamileler', 'Vegan'], notSuitableFor: ['Böbrek taşı olanlar'],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: false, isCampaign: false,
      rating: 4.7, reviewCount: 33, soldCount: 210, isActive: true,
    },
    {
      name: 'Mor Patlıcan', slug: 'mor-patlican',
      description: 'İnce kabuklu, az tohumlu Ege patlıcanı. Közlemesi, musakka ve imam bayıldı için mükemmel.',
      story: 'Geleneksel Ege patlıcan tohumu kullanılarak organik gübrelerle büyütülmüştür.',
      producer: yilmaz, category: 'sebze', tags: ['taze', 'organik', 'patlıcan'],
      images: ['https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=600&q=80'],
      price: 32, discountedPrice: 26, unit: 'kg', stock: 90, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş' },
      healthBenefits: ['Antioksidan', 'Kötü kolesterolü düşürür'],
      suitableFor: ['Herkes', 'Vegan'], notSuitableFor: [],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: false, isCampaign: true, campaignEndsAt: campaign, campaignOriginalPrice: 32,
      rating: 4.6, reviewCount: 22, soldCount: 145, isActive: true,
    },
    {
      name: 'Havuç', slug: 'organik-havuc',
      description: 'Toprak kokan taze havuç. Doğal ortamda yetişmiş, şekeri bol, çıtır çıtır.',
      story: 'Kuzey Ege\'nin derin, gevşek topraklarında yetiştirilen havuçlar hasat günü gönderilir.',
      producer: yilmaz, category: 'sebze', tags: ['taze', 'organik', 'havuç'],
      images: ['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&q=80'],
      price: 24, unit: 'kg', stock: 200, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş' },
      healthBenefits: ['Beta karoten', 'Göz sağlığı', 'A vitamini'],
      suitableFor: ['Herkes', 'Çocuklar', 'Vegan'], notSuitableFor: [],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: true, isCampaign: false,
      rating: 4.9, reviewCount: 56, soldCount: 400, isActive: true,
    },

    /* ─────────── MEYVE ─────────── */
    {
      name: 'Starking Elma', slug: 'starking-elma',
      description: 'Tatlı, çıtır ve kırmızı Starking elma. Göcek\'in serin dağ bahçelerinden doğrudan sofraya.',
      story: 'Ege\'nin dağ köylerinde 1800 metre yükseklikte yetişen bu elmalar, doğal soğuk hava sayesinde muhteşem lezzet kazanır.',
      producer: yilmaz, category: 'meyve', tags: ['taze', 'organik', 'elma', 'starking'],
      images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&q=80', 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80'],
      price: 55, unit: 'kg', stock: 180, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş', farmName: 'Yılmaz Organik Çiftliği' },
      healthBenefits: ['Lif kaynağı', 'Sindirim dostu', 'C vitamini'],
      suitableFor: ['Herkes', 'Çocuklar', 'Diyabetik'], notSuitableFor: [],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: true, isCampaign: false,
      rating: 4.9, reviewCount: 78, soldCount: 520, isActive: true,
    },
    {
      name: 'Taze Çilek', slug: 'taze-cilek',
      description: 'İlkbaharda hasat edilen, kırmızı, sulu ve aromalı organik çilek. Markettekilere benzemez!',
      story: 'Ege\'nin Nisan-Haziran döneminde güneşin altında olgunlaşan bu çilekler kimyasal ilaç görmez.',
      producer: yilmaz, category: 'meyve', tags: ['taze', 'organik', 'çilek'],
      images: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&q=80'],
      price: 80, discountedPrice: 65, unit: 'kg', stock: 60, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş' },
      healthBenefits: ['C vitamini', 'Antioksidan', 'Kalp sağlığı'],
      suitableFor: ['Herkes', 'Çocuklar', 'Vegan'], notSuitableFor: [],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: true, isCampaign: true, campaignEndsAt: campaign, campaignOriginalPrice: 80,
      rating: 4.9, reviewCount: 92, soldCount: 380, isActive: true,
    },
    {
      name: 'Taze İncir', slug: 'taze-incir',
      description: 'Ege\'nin ünlü beyaz inciri. Aydın\'ın güneşli bahçelerinden taze hasat, ağzınızda eriyecek.',
      story: 'Yüzlerce yıllık incir bahçelerinde doğal yollarla yetiştirilen bu incirler, Ege\'nin en değerli meyvesidir.',
      producer: yilmaz, category: 'meyve', tags: ['taze', 'organik', 'incir'],
      images: ['https://images.unsplash.com/photo-1601379327928-bedfaf9da2d0?w=600&q=80'],
      price: 95, unit: 'kg', stock: 45, minOrderQuantity: 1,
      origin: { city: 'Aydın', district: 'Germencik' },
      healthBenefits: ['Lif kaynağı', 'Kalsiyum', 'Demir', 'Sindirim dostu'],
      suitableFor: ['Herkes', 'Vegan'], notSuitableFor: ['Diyabetik (fazla tüketmemeli)'],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: true, isCampaign: false,
      rating: 4.8, reviewCount: 41, soldCount: 260, isActive: true,
    },
    {
      name: 'Kayısı', slug: 'organik-kayisi',
      description: 'Malatya\'nın güneşinde olgunlaşmış, bal gibi tatlı organik kayısı.',
      story: 'Malatya ovasının derin killi topraklarında yetişen bu kayısılar, yüzlerce yıllık geleneksel bahçelerde büyür.',
      producer: yilmaz, category: 'meyve', tags: ['taze', 'organik', 'kayısı'],
      images: ['https://images.unsplash.com/photo-1560439513-74b037a25d84?w=600&q=80'],
      price: 70, unit: 'kg', stock: 75, minOrderQuantity: 1,
      origin: { city: 'Malatya', district: 'Merkez' },
      healthBenefits: ['Beta karoten', 'A vitamini', 'Demir'],
      suitableFor: ['Herkes', 'Çocuklar', 'Vegan'], notSuitableFor: [],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: false, isCampaign: false,
      rating: 4.7, reviewCount: 35, soldCount: 190, isActive: true,
    },
    {
      name: 'Üzüm (Çekirdeksiz)', slug: 'cekirdeksiz-uzum',
      description: 'Manisa\'nın güneşinde büyümüş, tatlı ve sulu çekirdeksiz Sultani üzümü.',
      story: 'Ege\'nin en verimli bağlarından hasat edilen bu üzümler yıllarca kimyasal almamış toprakta yetişir.',
      producer: yilmaz, category: 'meyve', tags: ['taze', 'organik', 'üzüm', 'çekirdeksiz'],
      images: ['https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&q=80'],
      price: 60, unit: 'kg', stock: 100, minOrderQuantity: 1,
      origin: { city: 'Manisa', district: 'Alaşehir' },
      healthBenefits: ['Antioksidan', 'Resveratrol', 'Enerji'],
      suitableFor: ['Herkes', 'Sporcu', 'Vegan'], notSuitableFor: ['Diyabetik (sınırlı)'],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: false, isCampaign: false,
      rating: 4.7, reviewCount: 29, soldCount: 175, isActive: true,
    },

    /* ─────────── TAHIL ─────────── */
    {
      name: 'Tam Buğday Unu', slug: 'tam-bugday-unu',
      description: 'Taş değirmende öğütülmüş, kepekli tam buğday unu. Ekmek, börek ve tatlılar için ideal.',
      story: 'Konya ovasından gelen sertifikalı organik buğday, geleneksel taş değirmende öğütülüyor.',
      producer: doga, category: 'tahıl', tags: ['organik', 'un', 'buğday', 'tam tahıl'],
      images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80'],
      price: 65, unit: 'kg', stock: 300, minOrderQuantity: 2,
      origin: { city: 'Konya', district: 'Çumra' },
      healthBenefits: ['Lif', 'B vitamini', 'Demir', 'Tokluk hissi'],
      suitableFor: ['Herkes', 'Sporcu'], notSuitableFor: ['Gluten hassasiyeti', 'Çölyak'],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: false, isCampaign: false,
      rating: 4.8, reviewCount: 67, soldCount: 450, isActive: true,
    },
    {
      name: 'Yulaf Ezmesi', slug: 'organik-yulaf-ezmesi',
      description: 'Sabahları şişirmeden tüketilebilen organik yulaf ezmesi. Lif açısından son derece zengin.',
      story: 'Kuzey Anadolu\'nun serin iklimiyle yetiştirilen yulaf, minimale işlenerek paketlenmektedir.',
      producer: doga, category: 'tahıl', tags: ['organik', 'yulaf', 'kahvaltı', 'sağlıklı'],
      images: ['https://images.unsplash.com/photo-1614961233913-a5113a4a34ed?w=600&q=80'],
      price: 85, unit: 'kg', stock: 180, minOrderQuantity: 1,
      origin: { city: 'Kastamonu', district: 'Merkez' },
      healthBenefits: ['Beta-glukan', 'Kolesterol düşürücü', 'Uzun tokluk'],
      suitableFor: ['Herkes', 'Diyabetik', 'Sporcular', 'Kalp hastaları'], notSuitableFor: ['Gluten hassasiyeti'],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: true, isCampaign: false,
      rating: 4.9, reviewCount: 88, soldCount: 610, isActive: true,
    },

    /* ─────────── SÜT ÜRÜNLERİ ─────────── */
    {
      name: 'Köy Yoğurdu', slug: 'koy-yogurdu',
      description: 'Otlakta beslenen ineklerin sütünden yapılan, kaymaktan zengin, süzme Karadeniz köy yoğurdu.',
      story: 'Trabzon\'un yaylaları köyümüzdeki inekler, yaz boyunca çiçekli meralarda otlar. Sütleri katışıksız ve bereketlidir.',
      producer: anadolu, category: 'süt-ürünleri', tags: ['organik', 'yoğurt', 'köy', 'doğal'],
      images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80'],
      price: 120, unit: 'kg', stock: 60, minOrderQuantity: 1,
      origin: { city: 'Trabzon', district: 'Maçka', farmName: 'Anadolu Bahçesi' },
      healthBenefits: ['Probiyotik', 'Kalsiyum', 'Protein', 'Bağışıklık güçlendirici'],
      suitableFor: ['Herkes', 'Çocuklar', 'Yaşlılar'], notSuitableFor: ['Laktoz intoleransı'],
      certificates: ['Organik Ürün Belgesi'],
      isFeatured: true, isCampaign: false,
      rating: 4.9, reviewCount: 104, soldCount: 780, isActive: true,
    },
    {
      name: 'Kaşar Peyniri', slug: 'kaskaval-peyniri',
      description: 'Karadeniz meraları sütünden yapılan, 3 ay dinlendirilmiş el yapımı kaşar peyniri.',
      story: 'Büyükannemizden öğrendiğimiz geleneksel tarifle her gün taze sütten yapıyoruz.',
      producer: anadolu, category: 'süt-ürünleri', tags: ['organik', 'peynir', 'kaşar', 'el yapımı'],
      images: ['https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&q=80'],
      price: 220, unit: 'kg', stock: 40, minOrderQuantity: 1,
      origin: { city: 'Trabzon', district: 'Maçka' },
      healthBenefits: ['Kalsiyum', 'Protein', 'B12 vitamini'],
      suitableFor: ['Herkes', 'Çocuklar'], notSuitableFor: ['Laktoz intoleransı', 'Vegan'],
      certificates: ['Organik Ürün Belgesi'],
      isFeatured: true, isCampaign: false,
      rating: 4.8, reviewCount: 71, soldCount: 320, isActive: true,
    },
    {
      name: 'Tereyağı (Yayık)', slug: 'yayik-tereyagi',
      description: 'Geleneksel yayıkta çalkanan, katkısız, sarı renkli köy tereyağı.',
      story: 'Karadeniz yayla sütünden elde edilen kaymak, ahşap yayıkta çalkalanarak tereyağına dönüşür.',
      producer: anadolu, category: 'süt-ürünleri', tags: ['organik', 'tereyağı', 'köy', 'yayık'],
      images: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80'],
      price: 380, unit: 'kg', stock: 25, minOrderQuantity: 1,
      origin: { city: 'Trabzon', district: 'Maçka' },
      healthBenefits: ['Yağda çözünen vitaminler', 'K2 vitamini', 'CLA'],
      suitableFor: ['Herkes'], notSuitableFor: ['Laktoz intoleransı', 'Vegan'],
      certificates: ['Organik Ürün Belgesi'],
      isFeatured: false, isCampaign: false,
      rating: 4.9, reviewCount: 53, soldCount: 215, isActive: true,
    },

    /* ─────────── BAL & REÇEL ─────────── */
    {
      name: 'Çam Balı', slug: 'cam-bali',
      description: 'Muğla çam ormanlarından elde edilen, koyu renkli ve mineral açısından zengin çam balı.',
      story: 'Kazdağları\'nın çam ormanlarında arılarımız, hormonal salgı olan tatlandırıcı yerine gerçek çam özü toplar.',
      producer: anadolu, category: 'bal-recel', tags: ['organik', 'bal', 'çam', 'doğal'],
      images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80'],
      price: 280, unit: 'kg', stock: 50, minOrderQuantity: 1,
      origin: { city: 'Muğla', district: 'Köyceğiz' },
      healthBenefits: ['Antibakteriyal', 'Bağışıklık güçlendirici', 'Mineral kaynağı'],
      suitableFor: ['Herkes'], notSuitableFor: ['1 yaş altı bebekler', 'Diyabetik'],
      certificates: ['Organik Ürün Belgesi'],
      isFeatured: true, isCampaign: false,
      rating: 4.9, reviewCount: 127, soldCount: 670, isActive: true,
    },
    {
      name: 'Çiçek Balı', slug: 'cicek-bali',
      description: 'İlkbahar çiçeklerinden derlenen, açık renkli ve tatlı çiçek balı. Sabah kahvaltısının vazgeçilmezi.',
      story: 'Ege yayla çiçeklerinin açtığı dönemde arılarımız her türlü çiçekten nektar toplayarak bu eşsiz balı üretir.',
      producer: anadolu, category: 'bal-recel', tags: ['organik', 'bal', 'çiçek', 'süzme'],
      images: ['https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&q=80'],
      price: 200, unit: 'kg', stock: 70, minOrderQuantity: 1,
      origin: { city: 'Trabzon', district: 'Maçka' },
      healthBenefits: ['Enerji', 'Antibakteriyal', 'Boğaz rahatlatıcı'],
      suitableFor: ['Herkes'], notSuitableFor: ['1 yaş altı bebekler', 'Diyabetik'],
      certificates: ['Organik Ürün Belgesi'],
      isFeatured: false, isCampaign: false,
      rating: 4.8, reviewCount: 89, soldCount: 510, isActive: true,
    },
    {
      name: 'Çilek Reçeli', slug: 'cilek-receli',
      description: 'Bahçeden toplanan taze çilek ile az şekerli, meyve parçacıklı ev yapımı çilek reçeli.',
      story: 'Her yaz hasat ettiğimiz çileklerden annemizin tarifiyle yapılan reçel, katkısız ve koruyucusuz.',
      producer: anadolu, category: 'bal-recel', tags: ['organik', 'reçel', 'çilek', 'ev yapımı'],
      images: ['https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80'],
      price: 95, unit: 'kutu', stock: 90, minOrderQuantity: 1,
      origin: { city: 'Trabzon', district: 'Maçka' },
      healthBenefits: ['C vitamini', 'Antioksidan'],
      suitableFor: ['Herkes'], notSuitableFor: ['Diyabetik'],
      certificates: ['Organik Ürün Belgesi'],
      isFeatured: false, isCampaign: false,
      rating: 4.7, reviewCount: 44, soldCount: 280, isActive: true,
    },

    /* ─────────── ZEYTİNYAĞI ─────────── */
    {
      name: 'Sızma Zeytinyağı', slug: 'sizma-zeytinyagi',
      description: 'Ayvalık\'ın yüzlerce yıllık zeytin bahçelerinden soğuk sıkım sızma zeytinyağı. Asitliği %0.3\'ün altında.',
      story: 'Kasım ayında el ile hasat edilen zeytinler, 4 saat içinde taş baskı tesisimizde soğuk sıkılır.',
      producer: ege, category: 'zeytinyağı', tags: ['organik', 'zeytinyağı', 'sızma', 'soğuk sıkım'],
      images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80', 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80'],
      price: 450, unit: 'litre', stock: 120, minOrderQuantity: 1,
      origin: { city: 'Balıkesir', district: 'Ayvalık', farmName: 'Ege Zeytinliği' },
      healthBenefits: ['Kalp sağlığı', 'Antioksidan', 'Omega-9', 'Anti-inflamatuar'],
      suitableFor: ['Herkes', 'Kalp hastaları', 'Diyabetik'], notSuitableFor: [],
      certificates: ['PDO Sertifikası', 'Organik Tarım Sertifikası'],
      isFeatured: true, isCampaign: false,
      rating: 4.9, reviewCount: 215, soldCount: 1250, isActive: true,
    },
    {
      name: 'Naturel Zeytinyağı', slug: 'naturel-zeytinyagi',
      description: 'Günlük pişirme için ideal, meyve aromasıyla naturel sızma zeytinyağı. 5 litrelik ekonomik boy.',
      story: 'Aynı bahçelerden daha olgun dönemde hasat edilen zeytinlerden elde edilen bu yağ daha yumuşak aroma taşır.',
      producer: ege, category: 'zeytinyağı', tags: ['organik', 'zeytinyağı', 'naturel', 'pişirmelik'],
      images: ['https://images.unsplash.com/photo-1558818498-28c1e002b655?w=600&q=80'],
      price: 1800, unit: 'litre', stock: 50, minOrderQuantity: 1,
      origin: { city: 'Balıkesir', district: 'Ayvalık' },
      healthBenefits: ['Kalp sağlığı', 'Omega-9'],
      suitableFor: ['Herkes'], notSuitableFor: [],
      certificates: ['PDO Sertifikası'],
      isFeatured: false, isCampaign: false,
      rating: 4.8, reviewCount: 96, soldCount: 380, isActive: true,
    },

    /* ─────────── KURUYEMİŞ ─────────── */
    {
      name: 'Ceviz (İç)', slug: 'ic-ceviz',
      description: 'Kabuğundan çıkarılmış, taze ve yağlı iç ceviz. Yemek, pasta ve atıştırmalık için.',
      story: 'Şanlıurfa\'nın ceviz bahçelerinden elle toplanan cevizler, güneşte kurutularak kabuğu alınır.',
      producer: doga, category: 'kuruyemiş', tags: ['organik', 'ceviz', 'kuruyemiş'],
      images: ['https://images.unsplash.com/photo-1563412580953-f2e9eba6b7c2?w=600&q=80'],
      price: 320, unit: 'kg', stock: 85, minOrderQuantity: 1,
      origin: { city: 'Şanlıurfa', district: 'Merkez', farmName: 'Doğa\'nın Kalbi Çiftliği' },
      healthBenefits: ['Omega-3', 'Beyin sağlığı', 'Antioksidan', 'Protein'],
      suitableFor: ['Herkes', 'Sporcu', 'Vegan'], notSuitableFor: ['Fındık/ceviz alerjisi'],
      certificates: ['İyi Tarım Uygulamaları'],
      isFeatured: true, isCampaign: false,
      rating: 4.8, reviewCount: 73, soldCount: 430, isActive: true,
    },
    {
      name: 'Çiğ Badem', slug: 'cig-badem',
      description: 'İspanya çeşidi, iri taneli, taze çiğ badem. Sağlıklı atıştırmalık, diyet ve spor için vazgeçilmez.',
      story: 'Güneydoğu Anadolu\'nun bereketli topraklarından el hasadıyla toplanan bademler doğal ortamda kurutulur.',
      producer: doga, category: 'kuruyemiş', tags: ['organik', 'badem', 'çiğ', 'protein'],
      images: ['https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=600&q=80'],
      price: 280, unit: 'kg', stock: 100, minOrderQuantity: 1,
      origin: { city: 'Şanlıurfa', district: 'Merkez' },
      healthBenefits: ['E vitamini', 'Protein', 'Magnezyum', 'Kemik sağlığı'],
      suitableFor: ['Herkes', 'Sporcu', 'Diyabetik', 'Vegan'], notSuitableFor: ['Kuruyemiş alerjisi'],
      certificates: ['İyi Tarım Uygulamaları'],
      isFeatured: false, isCampaign: false,
      rating: 4.7, reviewCount: 58, soldCount: 310, isActive: true,
    },
    {
      name: 'Antep Fıstığı', slug: 'antep-fistigi',
      description: 'Gaziantep\'in kırmızılı-yeşilli meşhur fıstığı. Çiğ, tuzlanmamış ve katkısız.',
      story: 'Antep topraklarının bu eşsiz meyvesi, yıllar süren beklemenin ardından ağaç başında olgunlaşır.',
      producer: doga, category: 'kuruyemiş', tags: ['organik', 'fıstık', 'antep', 'kuruyemiş'],
      images: ['https://images.unsplash.com/photo-1608797178974-15b35a64ede9?w=600&q=80'],
      price: 520, unit: 'kg', stock: 60, minOrderQuantity: 1,
      origin: { city: 'Gaziantep', district: 'Islahiye' },
      healthBenefits: ['Protein', 'Sağlıklı yağ', 'Lif', 'Antioksidan'],
      suitableFor: ['Herkes', 'Sporcu', 'Vegan'], notSuitableFor: ['Kuruyemiş alerjisi'],
      certificates: ['İyi Tarım Uygulamaları'],
      isFeatured: true, isCampaign: false,
      rating: 4.9, reviewCount: 112, soldCount: 680, isActive: true,
    },
    {
      name: 'Fındık (İç)', slug: 'ic-findik',
      description: 'Giresun\'un meşhur tombul fındığı. İnce kabuklu, yağlı ve taze iç fındık.',
      story: 'Karadeniz\'in nemli iklimiyle yeşeren fındık bahçelerimizde her Eylül gerçek bir hasat şenliği yaşanır.',
      producer: doga, category: 'kuruyemiş', tags: ['organik', 'fındık', 'giresun', 'tombul'],
      images: ['https://images.unsplash.com/photo-1571680322279-a226e6a4cc2a?w=600&q=80'],
      price: 380, unit: 'kg', stock: 70, minOrderQuantity: 1,
      origin: { city: 'Giresun', district: 'Merkez' },
      healthBenefits: ['E vitamini', 'Mangan', 'Sağlıklı yağ', 'Protein'],
      suitableFor: ['Herkes', 'Vegan'], notSuitableFor: ['Kuruyemiş alerjisi'],
      certificates: ['İyi Tarım Uygulamaları'],
      isFeatured: false, isCampaign: false,
      rating: 4.8, reviewCount: 65, soldCount: 390, isActive: true,
    },

    /* ─────────── BAKLİYAT ─────────── */
    {
      name: 'Yeşil Mercimek', slug: 'yesil-mercimek',
      description: 'Güneydoğu\'nun bereketli topraklarından yetiştirilen iri taneli yeşil mercimek.',
      story: 'Harran ovasının derin topraklarında sulama yapılmaksızın yetişen bu mercimek, zengin protein içerir.',
      producer: doga, category: 'bakliyat', tags: ['organik', 'mercimek', 'yeşil', 'baklagil'],
      images: ['https://images.unsplash.com/photo-1515543904379-3d757abe528b?w=600&q=80'],
      price: 68, unit: 'kg', stock: 250, minOrderQuantity: 1,
      origin: { city: 'Şanlıurfa', district: 'Harran', farmName: 'Doğa\'nın Kalbi Çiftliği' },
      healthBenefits: ['Protein', 'Demir', 'Lif', 'Folik asit'],
      suitableFor: ['Herkes', 'Vegan', 'Vejetaryen', 'Sporcu'], notSuitableFor: [],
      certificates: ['İyi Tarım Uygulamaları'],
      isFeatured: false, isCampaign: false,
      rating: 4.7, reviewCount: 49, soldCount: 340, isActive: true,
    },
    {
      name: 'Nohut', slug: 'organik-nohut',
      description: 'Anadolu\'nun en değerli baklagili. İri taneli, bol proteinli ve lezzetli organik nohut.',
      story: 'Osmanlı\'dan bu yana ekilegelen geleneksel nohut tohumları ile yetiştirilen bu nohutlar, 24 saat suda bekletildiğinde mükemmel pişer.',
      producer: doga, category: 'bakliyat', tags: ['organik', 'nohut', 'baklagil', 'protein'],
      images: ['https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=600&q=80'],
      price: 72, unit: 'kg', stock: 200, minOrderQuantity: 1,
      origin: { city: 'Şanlıurfa', district: 'Merkez' },
      healthBenefits: ['Protein', 'Lif', 'Demir', 'Kan şekeri dengesi'],
      suitableFor: ['Herkes', 'Vegan', 'Diyabetik', 'Sporcu'], notSuitableFor: [],
      certificates: ['İyi Tarım Uygulamaları'],
      isFeatured: false, isCampaign: false,
      rating: 4.8, reviewCount: 62, soldCount: 410, isActive: true,
    },
    {
      name: 'Kuru Fasulye', slug: 'kuru-fasulye',
      description: 'Dermason çeşidi kuru fasulye. Türk mutfağının olmazsa olmazı, köy tarlasından sofraya.',
      story: 'Bolu\'nun dağ köylerinde yetişen bu fasulye çeşidi, geleneksel tohumların son temsilcilerindendir.',
      producer: doga, category: 'bakliyat', tags: ['organik', 'fasulye', 'dermason', 'baklagil'],
      images: ['https://images.unsplash.com/photo-1587404773352-3e2869e0f25f?w=600&q=80'],
      price: 75, unit: 'kg', stock: 180, minOrderQuantity: 1,
      origin: { city: 'Bolu', district: 'Göynük' },
      healthBenefits: ['Protein', 'Demir', 'Lif', 'Tokluk'],
      suitableFor: ['Herkes', 'Vegan', 'Vejetaryen'], notSuitableFor: [],
      certificates: ['İyi Tarım Uygulamaları'],
      isFeatured: false, isCampaign: false,
      rating: 4.7, reviewCount: 38, soldCount: 255, isActive: true,
    },
    {
      name: 'Barbunya', slug: 'organik-barbunya',
      description: 'Ege\'nin lekeli, benekli barbunyası. Zeytinyağlısı yapıldığında sofraların süsüdür.',
      story: 'İzmir köylerinde geleneksel yöntemle yetiştirilen bu baklagil, tam kuruduğunda hasat edilir.',
      producer: yilmaz, category: 'bakliyat', tags: ['organik', 'barbunya', 'baklagil'],
      images: ['https://images.unsplash.com/photo-1635209043628-4b63c1e6fa90?w=600&q=80'],
      price: 80, unit: 'kg', stock: 130, minOrderQuantity: 1,
      origin: { city: 'İzmir', district: 'Ödemiş' },
      healthBenefits: ['Protein', 'Lif', 'Demir'],
      suitableFor: ['Herkes', 'Vegan'], notSuitableFor: [],
      certificates: ['Organik Tarım Sertifikası'],
      isFeatured: false, isCampaign: false,
      rating: 4.6, reviewCount: 25, soldCount: 160, isActive: true,
    },
  ];
}

async function seed() {
  console.log('MongoDB\'ye bağlanıyor...');
  await mongoose.connect(MONGO_URI);
  console.log('Bağlantı kuruldu.\n');

  // Temizle
  await Producer.deleteMany({});
  await Product.deleteMany({});
  console.log('Mevcut veriler temizlendi.');

  // Üreticileri ekle
  const createdProducers = await Producer.insertMany(producers);
  console.log(`${createdProducers.length} üretici eklendi.`);

  const pIds = createdProducers.map(p => p._id as mongoose.Types.ObjectId);

  // Ürünleri ekle
  const products = makeProducts(pIds);
  const created = await Product.insertMany(products);
  console.log(`${created.length} ürün eklendi.\n`);

  // Özet
  const cats: Record<string, number> = {};
  products.forEach(p => { cats[p.category] = (cats[p.category] || 0) + 1; });
  console.log('Kategori dağılımı:');
  Object.entries(cats).forEach(([k, v]) => console.log(`  ${k}: ${v} ürün`));

  await mongoose.disconnect();
  console.log('\nBitti!');
}

seed().catch(e => { console.error(e); process.exit(1); });
